### ISSUE TITLE
ft_dbconnect.py initialize_database() fails on CREATE table

### ISSUE THREAD

**Issue by nodayoshikazu** [mikkorautiainen/fasttext-decrapifier#1]
Hi I found an issue. This line gives me an error. 

'    `input` text DEFAULT \'\', ' \     @line 8

The complaint is that it is not allowed to supply default value to a "text" type column. Changing it to below will resolve the issue.

'    `input` text, ' \

My MySQL is "Server version: 8.0.18 MySQL Community Server."

**Comment by mikkorautiainen** [comment]
Great work in finding a bug !
This is a feature difference between MySQL and MariaDB.  MariaDB has permitted defaults in text and blob fields since version 10.2.1, while MySQL's default configuration disallows it.

Would remove the 'input' and 'value' fields from the code. They were only needed in the development phase and aren’t written/read to in the current code.

**Comment by nodayoshikazu** [comment]
Okay great. Thanks for the modification. I am working on my JP fork and found it :)
